#ENC[AES256_GCM,data:evoN3wxMQU5n2W3ls1nlnqFHuNb/NlzRY6Dg2A0G4seqTX3Dh2sqr5ytoUa6SjUd/1nz7K8=,iv:PsqTtjyILgMm1nVyWIIuh7Oldcv4xwkY3dGV7M875Ks=,tag:FnUfaV5wATpMiM6TrMSxRQ==,type:comment]
#ENC[AES256_GCM,data:Vi2sKeDjia25P0mSejeWPR7XlykZvBjG7T8M37DZdZnX/UnkJggJBp4abRVgPjh7KWc9bem7sIrQrb//5tXnfwZfMy/fOiJeTOY=,iv:aNLJKWgqnmotreToDBfilR/Dx/aVSjMnUK3AGu6AaR4=,tag:bNcwfZbL96ZQP3e+8YamLw==,type:comment]
deploy_ssh_private_key: ENC[AES256_GCM,data:AcFeS2JdfP3oxg==,iv:xGY23cSmhX3H7tEUGBiJ3Ly9Rqsl4q+c1J6ly1R+w8I=,tag:/KwiiAQ8SEiUyhqRoozY8g==,type:str]
namecheap_ddns_password: ENC[AES256_GCM,data:pAFSmJiX9/uoGg==,iv:zethv81J7oR1n5WIe5AmIZ8n+w268uIVGeteZjnaTmY=,tag:LYWCd2LGsQKZM4K9tpEj9A==,type:str]
pi_host_keys:
    bastion: ENC[AES256_GCM,data:skLI3eEMdvg5/w==,iv:T9ySZYynX1v+BgS4neR3E3jxTJNvho99OHTOhWxf2Ag=,tag:MtHuwLcQuTmrJJ5T+8VhUQ==,type:str]
    dns: ENC[AES256_GCM,data:K4QG0+qm4PiAXw==,iv:ypnUaZyZx7xEA6B2etFTMUwarR4GQIArpjWKNodFmVo=,tag:WfEYH3NQFDgWgv7IF0d2hg==,type:str]
    bastion-backup: ENC[AES256_GCM,data:Wv3UnhhunOSx5g==,iv:94RAZYKSd/shM5r4ZN1i8gXMuVDMUQygqBbuk7f8amg=,tag:ZT0CQymh9P8W7RYBb9YdXw==,type:str]
    dns-backup: ENC[AES256_GCM,data:B8rsKBf+5KznFw==,iv:UnIiXUWLVUFTgTOUenzdD0JNDWA/rhWRaJr68JLPILs=,tag:TiuTfXkCYnF40bvSoDszew==,type:str]
sops:
    age:
        - recipient: age1heten6j3esrxmsvj808f8m9zt0ac6s3pvkg5ryjanpsdhgq33v3q3w86m7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSzBrKzlYeWNweWE4dXNQ
            am0xUVFGcFJQUzM4L3BMNHZNekk5dmdPRkZjCkZ0Yzc4clFCcUxmUjVvd3NkQ3JB
            UGdMUFB0RGk3WUVJWStteGtHWXI2cG8KLS0tIGVwOTJhdVRzOHFoWEV2OUJDcSta
            cGRaQ25ENFlJNis5SUhvTk1Pa1pYdDAKfUGPYzn7uKv6An7x0IpUwOycLU5MjlzL
            Cf7vCdvQ0U+GJuhhsvQpojRY74cGfwHR75KA4Z3kZnRyDWGQOgayTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T21:12:22Z"
    mac: ENC[AES256_GCM,data:ryw50h6GYtjzx8eQGCB9YR0mc3G7guvMqQb7yYIIxiXVYE1nhaC0s7GvJEEQQPj/iNxRO0+/AbWLyf7m/BRBktYMZPxZkeIJ1qciYMJavH+FVcSBguZL7IcLZiYFtnFv05JYdEVUjIZXtYZC+1by0GjbawhWkTVo8e1amEUCByE=,iv:RoaKEYysukrntBz8DhUTBhNV/3lDARsroYGkcxeyndw=,tag:NeozdyjxE8EVAbV37/1mkA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
